channels:
  - conda-forge
dependencies:
  - firefox
  - geckodriver
  - selenium
  - streamlit
  - numpy
  - altair
  - fake-useragent
  - datefinder
  - pandas
  - requests
  - beautifulsoup4
  - bs4
