channels:
  - conda-forge
  - mlgill
dependencies:
  - firefox
  - geckodriver
  - selenium
  - streamlit
  - numpy
  - altair
  - datefinder
  - pandas
  - requests
  - beautifulsoup4
  - bs4
  - pip:
    - fake-useragent
